using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

public partial class E_MonstaerData : BGEntity
{

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta)
		{
			return new E_MonstaerData(meta);
		}
		public BGEntity NewEntity(BGMetaEntity meta, BGId id)
		{
			return new E_MonstaerData(meta, id);
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5541529679651416247,12694959115498671276));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities
	{
		get
		{
			return MetaDefault.CountEntities;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Index];
		}
		set
		{
			_f_name[Index] = value;
		}
	}
	public System.Single f_HP
	{
		get
		{
			return _f_HP[Index];
		}
		set
		{
			_f_HP[Index] = value;
		}
	}
	public System.Single f_Speed
	{
		get
		{
			return _f_Speed[Index];
		}
		set
		{
			_f_Speed[Index] = value;
		}
	}
	public System.Single f_Att
	{
		get
		{
			return _f_Att[Index];
		}
		set
		{
			_f_Att[Index] = value;
		}
	}
	public System.Single f_AttSpeed
	{
		get
		{
			return _f_AttSpeed[Index];
		}
		set
		{
			_f_AttSpeed[Index] = value;
		}
	}
	public System.Single f_AttRange
	{
		get
		{
			return _f_AttRange[Index];
		}
		set
		{
			_f_AttRange[Index] = value;
		}
	}
	public System.Int32 f_BloodCnt
	{
		get
		{
			return _f_BloodCnt[Index];
		}
		set
		{
			_f_BloodCnt[Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(_ufle12jhs77_f_name==null || _ufle12jhs77_f_name.IsDeleted) _ufle12jhs77_f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5482723288733540880,5346102097766981796));
			return _ufle12jhs77_f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_HP;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_HP
	{
		get
		{
			if(_ufle12jhs77_f_HP==null || _ufle12jhs77_f_HP.IsDeleted) _ufle12jhs77_f_HP=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4950423235664500010,3926055540254285238));
			return _ufle12jhs77_f_HP;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_Speed;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_Speed
	{
		get
		{
			if(_ufle12jhs77_f_Speed==null || _ufle12jhs77_f_Speed.IsDeleted) _ufle12jhs77_f_Speed=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4954302159585886804,18182605959822801078));
			return _ufle12jhs77_f_Speed;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_Att;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_Att
	{
		get
		{
			if(_ufle12jhs77_f_Att==null || _ufle12jhs77_f_Att.IsDeleted) _ufle12jhs77_f_Att=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5386574837232014502,12302216657383446919));
			return _ufle12jhs77_f_Att;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_AttSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_AttSpeed
	{
		get
		{
			if(_ufle12jhs77_f_AttSpeed==null || _ufle12jhs77_f_AttSpeed.IsDeleted) _ufle12jhs77_f_AttSpeed=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5393305500155929347,9522114775973256611));
			return _ufle12jhs77_f_AttSpeed;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_AttRange;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_AttRange
	{
		get
		{
			if(_ufle12jhs77_f_AttRange==null || _ufle12jhs77_f_AttRange.IsDeleted) _ufle12jhs77_f_AttRange=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4623783464383546280,12041723202635966869));
			return _ufle12jhs77_f_AttRange;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_BloodCnt;
	public static BansheeGz.BGDatabase.BGFieldInt _f_BloodCnt
	{
		get
		{
			if(_ufle12jhs77_f_BloodCnt==null || _ufle12jhs77_f_BloodCnt.IsDeleted) _ufle12jhs77_f_BloodCnt=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(4880881682560427246,977739060326613947));
			return _ufle12jhs77_f_BloodCnt;
		}
	}
	private static readonly E_MonstaerData.Factory _factory0_PFS = new E_MonstaerData.Factory();
	private E_MonstaerData() : base(MetaDefault)
	{
	}
	private E_MonstaerData(BGId id) : base(MetaDefault, id)
	{
	}
	private E_MonstaerData(BGMetaEntity meta) : base(meta)
	{
	}
	private E_MonstaerData(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static E_MonstaerData FindEntity(Predicate<E_MonstaerData> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((E_MonstaerData) entity)) as E_MonstaerData;
	}
	public static List<E_MonstaerData> FindEntities(Predicate<E_MonstaerData> filter, List<E_MonstaerData> result=null, Comparison<E_MonstaerData> sort=null)
	{
		result = result ?? new List<E_MonstaerData>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((E_MonstaerData) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((E_MonstaerData) e1, (E_MonstaerData) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((E_MonstaerData) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<E_MonstaerData> action, Predicate<E_MonstaerData> filter=null, Comparison<E_MonstaerData> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((E_MonstaerData) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((E_MonstaerData) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((E_MonstaerData)e1,(E_MonstaerData)e2));
	}
	public static E_MonstaerData GetEntity(BGId entityId)
	{
		return (E_MonstaerData) MetaDefault.GetEntity(entityId);
	}
	public static E_MonstaerData GetEntity(int index)
	{
		return (E_MonstaerData) MetaDefault[index];
	}
	public static E_MonstaerData GetEntity(string entityName)
	{
		return (E_MonstaerData) MetaDefault.GetEntity(entityName);
	}
	public static E_MonstaerData NewEntity()
	{
		return (E_MonstaerData) MetaDefault.NewEntity();
	}
}
#pragma warning restore 414
