using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/MonsterData")]
public partial class MonsterData : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4996445916430306603,3638004110511368067));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public new System.String name
	{
		get
		{
			return _name[Entity.Index];
		}
		set
		{
			_name[Entity.Index] = value;
		}
	}
	public System.Int32 HP
	{
		get
		{
			return _HP[Entity.Index];
		}
		set
		{
			_HP[Entity.Index] = value;
		}
	}
	public System.Single Speed
	{
		get
		{
			return _Speed[Entity.Index];
		}
		set
		{
			_Speed[Entity.Index] = value;
		}
	}
	public System.Single Att
	{
		get
		{
			return _Att[Entity.Index];
		}
		set
		{
			_Att[Entity.Index] = value;
		}
	}
	public System.Single AttSpeed
	{
		get
		{
			return _AttSpeed[Entity.Index];
		}
		set
		{
			_AttSpeed[Entity.Index] = value;
		}
	}
	public System.Single AttRange
	{
		get
		{
			return _AttRange[Entity.Index];
		}
		set
		{
			_AttRange[Entity.Index] = value;
		}
	}
	public System.Single BloodCnt
	{
		get
		{
			return _BloodCnt[Entity.Index];
		}
		set
		{
			_BloodCnt[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name
	{
		get
		{
			if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5339696314988819107,13964914946922935447));
			return __name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt __HP;
	public static BansheeGz.BGDatabase.BGFieldInt _HP
	{
		get
		{
			if(__HP==null || __HP.IsDeleted) __HP=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5655245077357824210,1886622066788404127));
			return __HP;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __Speed;
	public static BansheeGz.BGDatabase.BGFieldFloat _Speed
	{
		get
		{
			if(__Speed==null || __Speed.IsDeleted) __Speed=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5400905824095379909,1147203316202728628));
			return __Speed;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __Att;
	public static BansheeGz.BGDatabase.BGFieldFloat _Att
	{
		get
		{
			if(__Att==null || __Att.IsDeleted) __Att=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4708013507654742826,12335998874427475085));
			return __Att;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __AttSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _AttSpeed
	{
		get
		{
			if(__AttSpeed==null || __AttSpeed.IsDeleted) __AttSpeed=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5576179052421708778,8892601362576125077));
			return __AttSpeed;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __AttRange;
	public static BansheeGz.BGDatabase.BGFieldFloat _AttRange
	{
		get
		{
			if(__AttRange==null || __AttRange.IsDeleted) __AttRange=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5496657371841676373,3802716890331060631));
			return __AttRange;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __BloodCnt;
	public static BansheeGz.BGDatabase.BGFieldFloat _BloodCnt
	{
		get
		{
			if(__BloodCnt==null || __BloodCnt.IsDeleted) __BloodCnt=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5335339494832708555,4838811026417368751));
			return __BloodCnt;
		}
	}
}
