using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/NpcReward")]
public partial class NpcReward : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5116796182263541059,14167254850889349299));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public new System.String name
	{
		get
		{
			return _name[Entity.Index];
		}
		set
		{
			_name[Entity.Index] = value;
		}
	}
	public System.Single Percent
	{
		get
		{
			return _Percent[Entity.Index];
		}
		set
		{
			_Percent[Entity.Index] = value;
		}
	}
	public System.Single GainPercent
	{
		get
		{
			return _GainPercent[Entity.Index];
		}
		set
		{
			_GainPercent[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name
	{
		get
		{
			if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5032724058970167161,12814021863223699891));
			return __name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __Percent;
	public static BansheeGz.BGDatabase.BGFieldFloat _Percent
	{
		get
		{
			if(__Percent==null || __Percent.IsDeleted) __Percent=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4957202088352575472,9650016986903505063));
			return __Percent;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __GainPercent;
	public static BansheeGz.BGDatabase.BGFieldFloat _GainPercent
	{
		get
		{
			if(__GainPercent==null || __GainPercent.IsDeleted) __GainPercent=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5726433121939456909,9732432347216093578));
			return __GainPercent;
		}
	}
}
