using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/TalkData")]
public partial class TalkData : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5730412772188250154,5372217023553720224));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public new System.String name
	{
		get
		{
			return _name[Entity.Index];
		}
		set
		{
			_name[Entity.Index] = value;
		}
	}
	public System.Collections.Hashtable Talk
	{
		get
		{
			return _Talk[Entity.Index];
		}
		set
		{
			_Talk[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name
	{
		get
		{
			if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5050986942272665288,3311936001745295546));
			return __name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldHashtable __Talk;
	public static BansheeGz.BGDatabase.BGFieldHashtable _Talk
	{
		get
		{
			if(__Talk==null || __Talk.IsDeleted) __Talk=(BansheeGz.BGDatabase.BGFieldHashtable) MetaDefault.GetField(new BGId(5422955025095893301,12354346714646676890));
			return __Talk;
		}
	}
}
