using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/TextTest")]
public partial class TextTest : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5104085017216792405,5759051022695425210));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public new System.String name
	{
		get
		{
			return _name[Entity.Index];
		}
		set
		{
			_name[Entity.Index] = value;
		}
	}
	public System.Collections.Hashtable Talkt
	{
		get
		{
			return _Talkt[Entity.Index];
		}
		set
		{
			_Talkt[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name
	{
		get
		{
			if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4620728507512292195,16572606750686491020));
			return __name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldHashtable __Talkt;
	public static BansheeGz.BGDatabase.BGFieldHashtable _Talkt
	{
		get
		{
			if(__Talkt==null || __Talkt.IsDeleted) __Talkt=(BansheeGz.BGDatabase.BGFieldHashtable) MetaDefault.GetField(new BGId(4837574275654267323,14902673064888142250));
			return __Talkt;
		}
	}
}
